# Generated by Django 3.2.4 on 2021-07-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_bgmodel_post_dt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgmodel',
            options={'ordering': ('-post_updated',)},
        ),
        migrations.RenameField(
            model_name='bgmodel',
            old_name='post_dt',
            new_name='post_created',
        ),
        migrations.AddField(
            model_name='bgmodel',
            name='post_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
