# Generated by Django 3.2.4 on 2021-07-31 05:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210728_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgmodel',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
